/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java101;

import java.util.ArrayList;
import java.util.List;

public class ThreeFiveMultiples {
    public String getGreeting() {
        return "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9." +
                " The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.";
    }

    public static void main(String[] args) {
        System.out.println(new ThreeFiveMultiples().getGreeting());
    }

    public int getSumOfThreeFiveMultiples(int maxNumber) {
        List<Integer> allMultiples = getMultiples(maxNumber);

        return allMultiples.stream()
                .reduce(0, (a,b) -> a + b);
    }

    private List<Integer> getMultiples(int maxNumber) {
        List<Integer> allMultiples = new ArrayList<>();

        for (int i = 0; i < maxNumber; i++) {
            if (i % 3 == 0 || i % 5 == 0){
                allMultiples.add(i);
            }
        }
        return allMultiples;
    }
}
