/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java101;

import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class ThreeFiveMultiplesTests {
    @Test public void testAppHasAGreeting() {
        ThreeFiveMultiples classUnderTest = new ThreeFiveMultiples();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testAppSum_3() {
        ThreeFiveMultiples classUnderTest = new ThreeFiveMultiples();
        assertEquals(3, classUnderTest.getSumOfThreeFiveMultiples(4));
    }

    @Test public void testAppSum_10() {
        ThreeFiveMultiples classUnderTest = new ThreeFiveMultiples();
        assertEquals(23, classUnderTest.getSumOfThreeFiveMultiples(10));
    }

    @Test public void testAppSum_1000() {
        ThreeFiveMultiples classUnderTest = new ThreeFiveMultiples();
        assertEquals(233168, classUnderTest.getSumOfThreeFiveMultiples(1000));
    }
}
